# Generated by Django 6.0.3 on 2026-03-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_customuser_managers_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='app_user',
        ),
    ]
